Script started on Wed Apr 10 22:19:29 2024
[1m[7m%[27m[1m[0m                                                                                ]7;file://Treys-MacBook-Air-4.local/Users/trendell/VStudio/Comp_2710/Project_5[0m[27m[24m[Jtrendell@Treys-MacBook-Air-4 Project_5 % [K[?2004heexit[?2004l

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...       5 completed.

Script done on Wed Apr 10 22:20:41 2024
